import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CreditCard, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getAdminEnrollmentById } from "@/lib/admin/actions/enrollments";

function money(value: number) { return value.toLocaleString("en-BD", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }

export default async function AdminEnrollmentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const enrollment = await getAdminEnrollmentById(id);
  if (!enrollment) notFound();
  return <div className="mx-auto max-w-4xl space-y-6 pb-10"><Button variant="ghost" size="sm" asChild className="-ml-2 gap-2"><Link href="/admin/enrollments"><ArrowLeft className="h-4 w-4" />Course Enrollments</Link></Button><div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 dark:border-slate-800 p-5 sm:flex-row sm:items-start sm:justify-between sm:p-6"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-600 dark:text-blue-400">Enrollment {enrollment.enrollment_code ? `· ${enrollment.enrollment_code}` : ""}</p><h1 className="mt-1 text-2xl font-bold text-slate-950">{enrollment.course_name}</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{enrollment.batch_name || "No batch assigned"} · {enrollment.status}</p></div><Button asChild><Link href={`/admin/payments/new?student_id=${enrollment.student_id}&enrollment_id=${enrollment.id}`}><CreditCard className="mr-2 h-4 w-4" />Receive Payment</Link></Button></div><div className="grid gap-px bg-slate-100 dark:bg-slate-800 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Final fee" value={`৳${money(enrollment.final_fee)}`} /><Metric label="Paid" value={`৳${money(enrollment.total_paid)}`} className="text-emerald-700 dark:text-emerald-500" /><Metric label="Current due" value={`৳${money(enrollment.current_due)}`} className="text-rose-700" /><Metric label="Payment progress" value={`${enrollment.payment_progress.toFixed(1)}%`} /></div><div className="grid gap-6 p-5 sm:grid-cols-2 sm:p-6"><div><p className="flex items-center gap-2 text-sm font-bold text-slate-900 dark:text-slate-50"><UserRound className="h-4 w-4 text-slate-500 dark:text-slate-400" />Student</p><p className="mt-3 font-semibold text-slate-950">{enrollment.student_name}</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{enrollment.student_mobile || "No mobile"}</p><Button variant="link" className="mt-2 h-auto px-0" asChild><Link href={`/admin/students/${enrollment.student_id}`}>Open student profile</Link></Button></div><div><p className="text-sm font-bold text-slate-900 dark:text-slate-50">Financial configuration</p><dl className="mt-3 space-y-2 text-sm"><Row label="Course fee" value={`৳${money(enrollment.course_fee)}`} /><Row label="Discount" value={`৳${money(enrollment.discount_amount)}`} /><Row label="Source" value={enrollment.source || "Legacy"} /><Row label="Enrolled" value={new Date(enrollment.enrolled_at).toLocaleDateString("en-BD")} /></dl></div></div></div></div>;
}
function Metric({ label, value, className = "" }: { label: string; value: string; className?: string }) { return <div className="bg-white dark:bg-slate-900 p-5"><p className="text-xs font-medium text-slate-500 dark:text-slate-400">{label}</p><p className={`mt-1 font-mono text-lg font-bold ${className}`}>{value}</p></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><dt className="text-slate-500 dark:text-slate-400">{label}</dt><dd className="font-medium text-slate-900 dark:text-slate-50">{value}</dd></div>; }
